# -*- coding: utf-8 -*-
"""fr4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xFMnL4IYvcz4KSgozvS9X3_RvHXWq94O
"""

import pandas  as pd

df = pandas.read_csv("https://www.football-data.co.uk/mmz4281/2324/EC.csv")
df.head(3)

df_ger = pandas.read_csv("https://www.football-data.co.uk/mmz4281/2526/D1.csv")
df_ger.head(3)

df_ger= df_ger.rename(columns={
    'FTHG': 'home_goals',
    'FTAG': 'away_goals',
    'FTR':'result',
    'HTHG' : 'home_half_goals',
    'HTAG' : 'away_half_goals'
})

root = "https://www.football-data.co.uk/mmz4281/"
leagues = ['D1','D2']
frames = []
for league in leagues:
  try:
    df = pandas.read_csv(root + "2324/"+ league + ".csv")
    frames.append(df)
  except Exception as e:
    print(e)

len(frames)

frames[1]

frames = []
for league in leagues:
  for season in range (15,26):
    season_str = str(season) + str(season + 1)
    try:
      df = pandas.read_csv(root + season_str + "/" + league + ".csv")
      frames.append(df)
    except Exception as e:
      print(e)
len(frames)

frames[20]

dict_coun = {
    'Spanish La Liga' : 'SP1',
    'Spanish Segunda Division' : 'SP2',
    'English Premier League' : 'E0',
    'English League 1' : 'E1',
    'English League 2' : 'E2',
    'German Bundesliga' : 'D1',
    'German 2. Bundesliga' : 'D2',
    'Italian Serie A' : 'I1',
    'Italian Serie B' : 'I2'
       }

dict_hist_data = {}
for league in dict_coun:
    frames = []
    for season in range(15,26):
        df = pandas.read_csv(root + str(season) + str(season + 1) + "/" + dict_coun[league] + ".csv", encoding = 'latin1')
        df.insert(1,'season', season)
        frames.append(df)
    df_frames = pd.concat(frames)
    dict_hist_data[league] = df_frames

dict_hist_data['German Bundesliga'].to_csv('german liga.csv')

df_frames

df_frames[(df_frames['Div'] == 'D1') & (df_frames['season'] == 21)].to_csv('german liga.csv')

"""pr

"""

df_frames= df_frames['']